name: linters

on:
  push:
    branches: [ 3.6.x ]
  pull_request:
    branches: [ 3.6.x ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install linters on ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install shellcheck

      - name: run Shellcheck
        run: |
          find . -name "*.sh" | xargs shellcheck || true

  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install linters on ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install cppcheck

      - name: run cppcheck
        run: |
          # cppcheck
          if ! [ -x "$(command -v cppcheck)" ]; then
            echo 'Error: cppcheck is not installed.' >&2
            exit 1
          fi
          CPPCHECK_OPTS='--error-exitcode=0 --force --quiet --suppressions-list=./static-analysis-suppressions'
          # we exclude some external projects
          CPPCHECK_EXCLUDES='-i ./nx-X11/extras/ -i nx-X11/programs/Xserver/GL/mesa* -i ./.pc -i ./nx-X11/.build-exports -i ./nx-X11/exports -i ./doc'
          echo "$(cppcheck --version):";
          cppcheck $CPPCHECK_OPTS $CPPCHECK_EXCLUDES .;
